
--EJERCICIO 1--



CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;


CREATE TABLE IF NOT EXISTS `mydb`.`ALUMNO` (
  `Cod_matricula` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cod_matricula`),
  UNIQUE INDEX `Cod_matricula_UNIQUE` (`Cod_matricula` ASC) ,
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `mydb`.`CURSO` (
  `Cod_curso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cod_curso`),
  UNIQUE INDEX `Cod_curso_UNIQUE` (`Cod_curso` ASC) )
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `mydb`.`PROFESOR` (
  `idPROFESOR` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `CURSO_Cod_curso` INT NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`idPROFESOR`, `CURSO_Cod_curso`),
  UNIQUE INDEX `idPROFESOR_UNIQUE` (`idPROFESOR` ASC),
  INDEX `fk_PROFESOR_CURSO1_idx` (`CURSO_Cod_curso` ASC) ,
  CONSTRAINT `fk_PROFESOR_CURSO1`
    FOREIGN KEY (`CURSO_Cod_curso`)
    REFERENCES `mydb`.`CURSO` (`Cod_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `mydb`.`alumno_curso` (
  `id` INT NOT NULL,
  `CURSO_Cod_curso` INT NOT NULL,
  `ALUMNO_Cod_matricula` INT NOT NULL,
  `PROFESOR_idPROFESOR` INT NOT NULL,
  `PROFESOR_CURSO_Cod_curso` INT NOT NULL,
  PRIMARY KEY (`id`, `CURSO_Cod_curso`, `ALUMNO_Cod_matricula`, `PROFESOR_idPROFESOR`, `PROFESOR_CURSO_Cod_curso`),
  INDEX `fk_alumno_curso_CURSO1_idx` (`CURSO_Cod_curso` ASC) ,
  INDEX `fk_alumno_curso_ALUMNO1_idx` (`ALUMNO_Cod_matricula` ASC) ,
  INDEX `fk_alumno_curso_PROFESOR1_idx` (`PROFESOR_idPROFESOR` ASC, `PROFESOR_CURSO_Cod_curso` ASC) ,
  CONSTRAINT `fk_alumno_curso_CURSO1`
    FOREIGN KEY (`CURSO_Cod_curso`)
    REFERENCES `mydb`.`CURSO` (`Cod_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_curso_ALUMNO1`
    FOREIGN KEY (`ALUMNO_Cod_matricula`)
    REFERENCES `mydb`.`ALUMNO` (`Cod_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_curso_PROFESOR1`
    FOREIGN KEY (`PROFESOR_idPROFESOR` , `PROFESOR_CURSO_Cod_curso`)
    REFERENCES `mydb`.`PROFESOR` (`idPROFESOR` , `CURSO_Cod_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



--EJERCICIO 2--



CREATE SCHEMA IF NOT EXISTS `ej2` DEFAULT CHARACTER SET utf8 ;
USE `ej2` ;


CREATE TABLE IF NOT EXISTS `ej2`.`EMPLEADO` (
  `idEMPLEADO` INT NOT NULL,
  `nombre_empleado` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `fecha_alta` DATE NOT NULL,
  PRIMARY KEY (`idEMPLEADO`))
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `ej2`.`LOCALIDAD` (
  `codigo_localidad` INT NOT NULL,
  `nombre_localidad` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  `EMPLEADO_idEMPLEADO` INT NOT NULL,
  PRIMARY KEY (`codigo_localidad`, `EMPLEADO_idEMPLEADO`),
  UNIQUE INDEX `codigo_localidad_UNIQUE` (`codigo_localidad` ASC),
  INDEX `fk_LOCALIDAD_EMPLEADO1_idx` (`EMPLEADO_idEMPLEADO` ASC) ,
  CONSTRAINT `fk_LOCALIDAD_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_idEMPLEADO`)
    REFERENCES `ej2`.`EMPLEADO` (`idEMPLEADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `ej2`.`PROVINCIA` (
  `idPROVINCIA` INT NOT NULL,
  `nombre_provincia` VARCHAR(45) NOT NULL,
  `LOCALIDAD_codigo_localidad` INT NOT NULL,
  PRIMARY KEY (`idPROVINCIA`, `LOCALIDAD_codigo_localidad`),
  UNIQUE INDEX `idPROVINCIA_UNIQUE` (`idPROVINCIA` ASC),
  INDEX `fk_PROVINCIA_LOCALIDAD1_idx` (`LOCALIDAD_codigo_localidad` ASC),
  CONSTRAINT `fk_PROVINCIA_LOCALIDAD1`
    FOREIGN KEY (`LOCALIDAD_codigo_localidad`)
    REFERENCES `ej2`.`LOCALIDAD` (`codigo_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `ej2`.`PAIS` (
  `idPAIS` INT NOT NULL,
  `nombre_pais` VARCHAR(45) NOT NULL,
  `PROVINCIA_idPROVINCIA` INT NOT NULL,
  PRIMARY KEY (`idPAIS`, `PROVINCIA_idPROVINCIA`),
  UNIQUE INDEX `idPAIS_UNIQUE` (`idPAIS` ASC) ,
  UNIQUE INDEX `nombre_pais_UNIQUE` (`nombre_pais` ASC) ,
  INDEX `fk_PAIS_PROVINCIA_idx` (`PROVINCIA_idPROVINCIA` ASC) ,
  CONSTRAINT `fk_PAIS_PROVINCIA`
    FOREIGN KEY (`PROVINCIA_idPROVINCIA`)
    REFERENCES `ej2`.`PROVINCIA` (`idPROVINCIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



--EJERCICIO 3--



CREATE SCHEMA IF NOT EXISTS `ej3` DEFAULT CHARACTER SET utf8 ;
USE `ej3` ;

CREATE TABLE IF NOT EXISTS `ej3`.`AVAL_CLIENTE` (
  `idCLIENTE` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idCLIENTE`),
  UNIQUE INDEX `idCLIENTE_UNIQUE` (`idCLIENTE` ASC) )
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `ej3`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(60) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `AVAL_CLIENTE_idCLIENTE` INT NOT NULL,
  PRIMARY KEY (`idCLIENTE`, `AVAL_CLIENTE_idCLIENTE`),
  UNIQUE INDEX `idCLIENTE_UNIQUE` (`idCLIENTE` ASC) ,
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) ,
  INDEX `fk_CLIENTE_AVAL_CLIENTE1_idx` (`AVAL_CLIENTE_idCLIENTE` ASC),
  CONSTRAINT `fk_CLIENTE_AVAL_CLIENTE1`
    FOREIGN KEY (`AVAL_CLIENTE_idCLIENTE`)
    REFERENCES `ej3`.`AVAL_CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `ej3`.`RESERVAS` (
  `idRESERVAS` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NOT NULL,
  `fecha_final` DATE NOT NULL,
  `precio_total` VARCHAR(45) NOT NULL,
  `gasolina` VARCHAR(45) NOT NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  `coches_reservados` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRESERVAS`, `CLIENTE_idCLIENTE`),
  INDEX `fk_RESERVAS_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) ,
  UNIQUE INDEX `idRESERVAS_UNIQUE` (`idRESERVAS` ASC) ,
  CONSTRAINT `fk_RESERVAS_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `ej3`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `ej3`.`COCHES` (
  `idCOCHES` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `precio_hora` VARCHAR(45) NOT NULL,
  `RESERVAS_idRESERVAS` INT NOT NULL,
  PRIMARY KEY (`idCOCHES`, `RESERVAS_idRESERVAS`),
  UNIQUE INDEX `idCOCHES_UNIQUE` (`idCOCHES` ASC) ,
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) ,
  INDEX `fk_COCHES_RESERVAS1_idx` (`RESERVAS_idRESERVAS` ASC) ,
  CONSTRAINT `fk_COCHES_RESERVAS1`
    FOREIGN KEY (`RESERVAS_idRESERVAS`)
    REFERENCES `ej3`.`RESERVAS` (`idRESERVAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

